# Use the lightweight Nginx web server
FROM nginx:alpine

# Copy your HTML files into Nginx's public web directory
COPY . /usr/share/nginx/html

# Expose standard HTTP port 80 (Internal to the container)
EXPOSE 80